In [1]:
import pandas as pd
import sklearn as sk
from sklearn.neighbors import KNeighborsRegressor

In [8]:
k_list = range(1, 457)
k_MSE_tuples = []

df = pd.read_csv(r'F:\Educational Data\Simplilearn\ML\Files\datasets\boston.csv')

print(df.shape)
df.head()

(506, 14)

,crime_rate,proportion_res_land,proportion_business,"river""",NO,avg_rooms,proportion_units,distance,accessibility,property_tax,pupil_teacher_ratio,proportion_blacks,lower_status,value
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [9]:
df.describe()

,crime_rate,proportion_res_land,proportion_business,"river""",NO,avg_rooms,proportion_units,distance,accessibility,property_tax,pupil_teacher_ratio,proportion_blacks,lower_status,value
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677082,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [10]:
cols = df.columns.tolist()
cols

['crime_rate',
 'proportion_res_land',
 'proportion_business',
 'river"',
 'NO',
 'avg_rooms',
 'proportion_units',
 'distance',
 'accessibility',
 'property_tax',
 'pupil_teacher_ratio',
 'proportion_blacks',
 'lower_status',
 'value']

In [11]:
X = df[cols[:-1]]
y = df[cols[-1]]

X_train = X.iloc[:(len(df)-50),]
y_train = y.iloc[:(len(df)-50),]

X_test = X.iloc[(len(df)-50):,]
y_test = y.iloc[(len(df)-50):,]

print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(456, 13) (456,) (50, 13) (50,)

In [12]:
for k in k_list:
    algo = KNeighborsRegressor(n_neighbors=k)
    
    algo.fit(X_train, y_train)
    
    predictions = algo.predict(X_test)
    
    MSE = sk.metrics.mean_squared_error(y_test, predictions)
    
    k_MSE_tuples.append((k, MSE))

In [13]:
k_MSE_tuples

[(1, 29.299199999999992),
 (2, 24.532349999999994),
 (3, 22.003244444444434),
 (4, 25.753774999999997),
 (5, 26.199511999999995),
 (6, 24.440900000000003),
 (7, 24.614844897959188),
 (8, 22.819918750000003),
 (9, 24.265634567901234),
 (10, 22.466314),
 (11, 23.035611570247937),
 (12, 24.952604166666674),
 (13, 23.773740828402374),
 (14, 24.387815306122455),
 (15, 27.16195644444445),
 (16, 25.310738281249996),
 (17, 24.742864359861592),
 (18, 25.761079629629627),
 (19, 27.536523545706363),
 (20, 27.362319),
 (21, 27.636767346938765),
 (22, 29.08414545454545),
 (23, 30.72338071833648),
 (24, 30.59721354166666),
 (25, 30.55123424),
 (26, 31.484486390532542),
 (27, 32.280383813443066),
 (28, 33.466578826530615),
 (29, 33.51196837098692),
 (30, 33.53000133333333),
 (31, 32.78647221644121),
 (32, 32.042155859375),
 (33, 31.766151515151513),
 (34, 30.539863840830446),
 (35, 30.5083386122449),
 (36, 30.227788580246916),
 (37, 30.199297297297303),
 (38, 29.615180332409977),
 (39, 28.64333767258383),
 (40, 28.80408125),
 (41, 29.22108423557406),
 (42, 28.729833446712014),
 (43, 27.714791346673877),
 (44, 27.140267768595034),
 (45, 26.386981925925916),
 (46, 26.06319631379962),
 (47, 25.9654873698506),
 (48, 25.56782907986111),
 (49, 24.762915368596417),
 (50, 24.539485119999995),
 (51, 24.404018685121105),
 (52, 24.157425221893494),
 (53, 24.125022356710573),
 (54, 22.76689362139918),
 (55, 22.858643702479345),
 (56, 22.81462786989796),
 (57, 22.81603102493075),
 (58, 23.180889060642095),
 (59, 23.120600114909504),
 (60, 23.066565833333325),
 (61, 22.866184359043263),
 (62, 22.647370135275747),
 (63, 22.697309347442665),
 (64, 22.714613964843746),
 (65, 22.651204544378697),
 (66, 22.58840353535353),
 (67, 22.86824651370015),
 (68, 23.151729065743947),
 (69, 23.24120928376391),
 (70, 23.118822571428566),
 (71, 22.76427930966078),
 (72, 22.80532592592592),
 (73, 22.62555815349971),
 (74, 22.737162892622347),
 (75, 22.59480192),
 (76, 22.49735207756232),
 (77, 22.603416225333106),
 (78, 22.596723142669298),
 (79, 22.665094151578273),
 (80, 22.55286184375),
 (81, 22.54005096784027),
 (82, 22.41477816775729),
 (83, 22.441828683408335),
 (84, 22.414434438775505),
 (85, 22.402442186851207),
 (86, 22.238509031909135),
 (87, 22.10078345884529),
 (88, 22.126811570247934),
 (89, 22.038303168791813),
 (90, 21.938817580246916),
 (91, 21.781063808718756),
 (92, 21.7145429584121),
 (93, 21.661049786102435),
 (94, 21.620855183340872),
 (95, 21.550280886426584),
 (96, 21.468573719618053),
 (97, 21.32286950791795),
 (98, 21.287106247396913),
 (99, 21.103140699928577),
 (100, 20.859492639999996),
 (101, 20.3612235467111),
 (102, 19.93974769319492),
 (103, 19.68834187953624),
 (104, 19.75796904585799),
 (105, 19.368054312925167),
 (106, 19.016021057315765),
 (107, 18.801209939732725),
 (108, 18.68565871056241),
 (109, 18.440007642454336),
 (110, 18.146838330578507),
 (111, 18.073259215972723),
 (112, 18.139936304209183),
 (113, 18.121133244576704),
 (114, 18.06311312711603),
 (115, 18.122068400756138),
 (116, 18.211118683115327),
 (117, 18.303185155964634),
 (118, 18.385747945992524),
 (119, 18.55365718522702),
 (120, 18.59012977777778),
 (121, 18.603833303736085),
 (122, 18.561662308519217),
 (123, 18.475211223478087),
 (124, 18.539335678980226),
 (125, 18.6506656256),
 (126, 18.517890765936002),
 (127, 18.554677524955046),
 (128, 18.668214135742186),
 (129, 18.634124896340364),
 (130, 18.488956911242603),
 (131, 18.43755652933978),
 (132, 18.501901033057845),
 (133, 18.446663157894736),
 (134, 18.46886767654265),
 (135, 18.35812668312757),
 (136, 18.343467906574396),
 (137, 18.252681421492884),
 (138, 18.25788036126864),
 (139, 18.31256321101392),
 (140, 18.349107275510207),
 (141, 18.382853860469794),
 (142, 18.45712634397937),
 (143, 18.612341884688735),
 (144, 18.735579513888887),
 (145, 18.845141136741976),
 (146, 18.91307321261025),
 (147, 18.878896635661064),
 (148, 18.867148429510596),
 (149, 18.958449322102606),
 (150, 18.964760782222214),
 (151, 18.99086383930529),
 (152, 19.062098363919674),
 (153, 19.11705591012004),
 (154, 19.161265542249954),
 (155, 19.257120932362124),
 (156, 19.356058267587112),
 (157, 19.554106008357333),
 (158, 19.675158596378786),
 (159, 19.68527569320834),
 (160, 19.738776890625),
 (161, 19.89671224875584),
 (162, 20.046568160341415),
 (163, 20.176663615491744),
 (164, 20.246528115704937),
 (165, 20.29608904315886),
 (166, 20.33199356945856),
 (167, 20.387031051669123),
 (168, 20.388179280045353),
 (169, 20.375739820034315),
 (170, 20.3660305467128),
 (171, 20.396912362778288),
 (172, 20.524600696322338),
 (173, 20.47624828761402),
 (174, 20.455175789404144),
 (175, 20.414397165714284),
 (176, 20.326753008780994),
 (177, 20.3075604519774),
 (178, 20.444978784244412),
 (179, 20.499601891326737),
 (180, 20.471396777777777),
 (181, 20.50455092335398),
 (182, 20.614826597029346),
 (183, 20.761866356116933),
 (184, 20.794568744092626),
 (185, 20.864522302410514),
 (186, 20.95107148225228),
 (187, 20.91354133089307),
 (188, 21.010490827297417),
 (189, 20.96853752134598),
 (190, 21.005473379501385),
 (191, 21.027808793618597),
 (192, 21.075747043185764),
 (193, 21.09563917420602),
 (194, 21.10006937506643),
 (195, 21.241952620644305),
 (196, 21.236810693461056),
 (197, 21.222274554871298),
 (198, 21.28167036526885),
 (199, 21.348144703416573),
 (200, 21.353950624999992),
 (201, 21.40664781564812),
 (202, 21.518870649936275),
 (203, 21.5838118275134),
 (204, 21.58758780276816),
 (205, 21.67470336704342),
 (206, 21.746303680837027),
 (207, 21.79998079301734),
 (208, 21.89591972078402),
 (209, 21.96537839793045),
 (210, 22.067177473922904),
 (211, 22.164058165809383),
 (212, 22.22044512281951),
 (213, 22.222735308250115),
 (214, 22.255336876583105),
 (215, 22.32444481557598),
 (216, 22.44300645147463),
 (217, 22.56103477245217),
 (218, 22.582325574446596),
 (219, 22.62912971789579),
 (220, 22.59082975619835),
 (221, 22.56717436579923),
 (222, 22.625915335605878),
 (223, 22.62834658649883),
 (224, 22.600338277264026),
 (225, 22.51524347654321),
 (226, 22.437956813376147),
 (227, 22.449544567136947),
 (228, 22.465951192674666),
 (229, 22.536468480768857),
 (230, 22.654418355387524),
 (231, 22.70080603436967),
 (232, 22.85020286489298),
 (233, 22.87054157932546),
 (234, 22.899086905544596),
 (235, 23.082157551833408),
 (236, 23.16027460858948),
 (237, 23.21024254660044),
 (238, 23.39325259868653),
 (239, 23.508564923583275),
 (240, 23.690730520833334),
 (241, 23.848943027840438),
 (242, 23.943687965302914),
 (243, 24.253927365408394),
 (244, 24.326776142166086),
 (245, 24.53357313119534),
 (246, 24.657724912419862),
 (247, 24.693330905276284),
 (248, 24.812954802939643),
 (249, 25.00433172368188),
 (250, 25.093866918400003),
 (251, 25.211559003825343),
 (252, 25.310357501889648),
 (253, 25.421656257713767),
 (254, 25.46070626511253),
 (255, 25.575592086120718),
 (256, 25.721045272827155),
 (257, 25.848771875425818),
 (258, 25.895107715882453),
 (259, 25.98660090338546),
 (260, 26.018776526627217),
 (261, 26.085962587161085),
 (262, 26.088804816152905),
 (263, 26.095938455088266),
 (264, 26.150443996786045),
 (265, 26.195926954788185),
 (266, 26.26558297246877),
 (267, 26.370290454347796),
 (268, 26.386450874359543),
 (269, 26.38313360511878),
 (270, 26.39839914403292),
 (271, 26.394076613880532),
 (272, 26.422674418793257),
 (273, 26.473201320291434),
 (274, 26.53597716447333),
 (275, 26.623963237024793),
 (276, 26.700769428691448),
 (277, 26.81004023511319),
 (278, 26.935098982971898),
 (279, 27.03383777443763),
 (280, 27.069887298469386),
 (281, 27.06525262851281),
 (282, 27.129114876012274),
 (283, 27.184036878972144),
 (284, 27.17530112080937),
 (285, 27.261585297630035),
 (286, 27.25512535576312),
 (287, 27.261476196141754),
 (288, 27.207704938271604),
 (289, 27.201461665928328),
 (290, 27.21391846373365),
 (291, 27.21158855233169),
 (292, 27.370408327078252),
 (293, 27.47781280620625),
 (294, 27.55292098199824),
 (295, 27.55891775237001),
 (296, 27.57282145498539),
 (297, 27.613457733337867),
 (298, 27.622458211341836),
 (299, 27.60155672531627),
 (300, 27.621616000000003),
 (301, 27.65857583470381),
 (302, 27.72270865312925),
 (303, 27.793390482414583),
 (304, 27.77422473381233),
 (305, 27.791608531040048),
 (306, 27.80201934939553),
 (307, 27.8595491113964),
 (308, 27.86816819868443),
 (309, 27.91407957185199),
 (310, 27.929182353798122),
 (311, 27.934641089318756),
 (312, 27.955247974194613),
 (313, 27.920170186487564),
 (314, 27.950660162684084),
 (315, 27.959177058201067),
 (316, 28.021268684906264),
 (317, 28.074393664978256),
 (318, 28.10041002729323),
 (319, 28.086813350890814),
 (320, 28.109284062499995),
 (321, 28.120889372191662),
 (322, 28.163471760348763),
 (323, 28.22028604894133),
 (324, 28.26167728623686),
 (325, 28.36727083171598),
 (326, 28.430268583687756),
 (327, 28.513059188807528),
 (328, 28.573254482079115),
 (329, 28.621013004314456),
 (330, 28.578556907254367),
 (331, 28.53998588183751),
 (332, 28.587211456670058),
 (333, 28.6991800196593),
 (334, 28.794767867259488),
 (335, 28.805610833593228),
 (336, 28.870828551941603),
 (337, 28.935921364104633),
 (338, 28.996160752424636),
 (339, 29.076794330018014),
 (340, 29.12125244636678),
 (341, 29.223947988063397),
 (342, 29.24926173352484),
 (343, 29.275336398949413),
 (344, 29.26671971842888),
 (345, 29.29189862969964),
 (346, 29.352975196297912),
 (347, 29.38262156981621),
 (348, 29.408037828643156),
 (349, 29.409860498682278),
 (350, 29.5485923722449),
 (351, 29.60020001136355),
 (352, 29.689467110020665),
 (353, 29.737123867457402),
 (354, 29.80384868173258),
 (355, 29.812895560404677),
 (356, 29.832921163678826),
 (357, 29.859021381101456),
 (358, 29.90810732811085),
 (359, 29.897753897005757),
 (360, 29.908135393518524),
 (361, 29.95646386691325),
 (362, 29.94880151246909),
 (363, 29.94350902412555),
 (364, 30.02070680624321),
 (365, 30.116850343404007),
 (366, 30.36707515751441),
 (367, 30.51574166858466),
 (368, 30.71935540081521),
 (369, 30.8607869081455),
 (370, 31.037958078889687),
 (371, 31.184146963477446),
 (372, 31.240869944502254),
 (373, 31.391474801083888),
 (374, 31.485936528067715),
 (375, 31.515194943999994),
 (376, 31.63452577099366),
 (377, 31.701331996988653),
 (378, 31.75369533187761),
 (379, 31.846695848678305),
 (380, 31.916953513850412),
 (381, 31.973586460550692),
 (382, 32.02840454346097),
 (383, 32.113031320685245),
 (384, 32.099843021647146),
 (385, 32.13412668848035),
 (386, 32.13860354237697),
 (387, 32.193811292056424),
 (388, 32.4874458098629),
 (389, 32.45391394320683),
 (390, 32.472957004602236),
 (391, 32.53751965908125),
 (392, 32.564919864119126),
 (393, 32.59426727657673),
 (394, 32.608557009971925),
 (395, 32.67187386508572),
 (396, 32.71197091368228),
 (397, 32.70315993756701),
 (398, 32.71622853589555),
 (399, 32.71819080910296),
 (400, 32.71488236),
 (401, 32.759664640145274),
 (402, 32.79917569490854),
 (403, 32.80854628992236),
 (404, 32.933302413979014),
 (405, 32.99783607742722),
 (406, 32.92995891310151),
 (407, 32.95189043217888),
 (408, 32.85666901432142),
 (409, 32.930089969572144),
 (410, 32.94236401427721),
 (411, 32.90704533953741),
 (412, 32.834817372042586),
 (413, 32.7430300910482),
 (414, 32.68948380592312),
 (415, 32.62759520278705),
 (416, 32.57650273784209),
 (417, 32.60085830501067),
 (418, 32.56427027540578),
 (419, 32.598735435546615),
 (420, 32.54124155215418),
 (421, 32.545274307863295),
 (422, 32.58315965499426),
 (423, 32.55807538297311),
 (424, 32.63313568329476),
 (425, 32.666150355709334),
 (426, 32.757199034583074),
 (427, 32.83923145632347),
 (428, 32.891159751943384),
 (429, 32.96934584032904),
 (430, 33.1219333931855),
 (431, 33.17651639902884),
 (432, 33.426736634087796),
 (433, 33.54296351145934),
 (434, 33.71388482660495),
 (435, 33.82845096578148),
 (436, 33.980844017759445),
 (437, 34.15740586587352),
 (438, 34.462105749463106),
 (439, 34.79104739701434),
 (440, 34.81449626652892),
 (441, 34.87920366513953),
 (442, 34.970822879343174),
 (443, 35.10136488542617),
 (444, 35.207739252089915),
 (445, 35.303207548541856),
 (446, 35.437855430432954),
 (447, 35.649075482085394),
 (448, 35.684395973174425),
 (449, 35.66953080193054),
 (450, 35.65038028345679),
 (451, 35.60384785915507),
 (452, 35.5993512207299),
 (453, 35.55236443138458),
 (454, 35.50104986609481),
 (455, 35.844242654751845),
 (456, 35.92813347376114)]

In [15]:
lowest_MSE = None

for each_tuple in k_MSE_tuples:
    if lowest_MSE is None:
        best_k     = each_tuple[0]
        lowest_MSE = each_tuple[1]
    else:
        if each_tuple[1] < lowest_MSE:
            best_k = each_tuple[0]
            lowest_MSE = each_tuple[1]

# Print the best MSE and k

print( "Lowest MSE for Boston dataset using k-nearest neighbors is %s, with k as %s." \
      "\n(Considering k-values in the range of 1 to %s)" % (lowest_MSE, best_k, k_list[-1]))

# print "MSE for Boston Dataset using Linear Regression is" , lowest_MSE

Lowest MSE for Boston dataset using k-nearest neighbors is 18.06311312711603, with k as 114.
(Considering k-values in the range of 1 to 456)

#### compare with linear regression

In [10]:
import pandas as pd
import sklearn as sk
from sklearn import linear_model

In [11]:
df = pd.read_csv(r'E:\MYLEARN\2-ANALYTICS-DataScience\datasets\boston.csv')

print(df.shape)
df.head()

(506, 14)

,crime_rate,proportion_res_land,proportion_business,"river""",NO,avg_rooms,proportion_units,distance,accessibility,property_tax,pupil_teacher_ratio,proportion_blacks,lower_status,value
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [12]:
algo = linear_model.LinearRegression()

In [13]:
cols = df.columns.tolist()

X = df[cols[:-1]]
y = df[cols[-1]]

X_train = X.iloc[:(len(df)-50),]
y_train = y.iloc[:(len(df)-50),]

X_test = X.iloc[(len(df)-50):,]
y_test = y.iloc[(len(df)-50):,]

print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(456, 13) (456,) (50, 13) (50,)

In [14]:
algo.fit (X_train, y_train)
predictions = algo.predict(X_test)

MSE = sk.metrics.mean_squared_error(y_test, predictions)

print ("MSE for Boston dataset using linear regression is" , MSE)

MSE for Boston dataset using linear regression is 10.960410679422822

# We see that for this particular dataset, linear regression  outperforms k-nearest neighbors.